// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"209ac797ecdb83c26458581b43cc00fc9b39e45ad9c719477cbf35cc627ab498ade054943b796b910c499eaa9a2f290f99fd34dda1329bb41cec44bccf22582b"}}
];
